/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code;
import java.io.FileNotFoundException;
import code.Quote;
import code.QuoteGenerator;


public class App {
    public static void main(String[] args) {
        try {
            QuoteGenerator quoteGenerator = new QuoteGenerator("C:/Users/soomr/Documents/Projects/Code-401/app/src/main/resources/recentquotes.json");
            Quote quote = quoteGenerator.getRandomQuote();
            System.out.println(quote.getQuote() + " - " + quote.getAuthor());
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}