/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import java.io.FileNotFoundException;



public class App {
    public static void main(String[] args) {
        try {
            QuoteGenerator quoteGenerator = new QuoteGenerator("app/src/main/resources/recentquotes.json");
            Quote quote = quoteGenerator.getRandomQuote();
            System.out.println(quote.getQuote() + " - " + quote.getAuthor());
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}